Add cleanup/reset to script, and exit code.

diff --git a/gitlab-lib.yaml b/gitlab-lib.yaml
--- a/gitlab-lib.yaml
+++ b/gitlab-lib.yaml
@@ -120,9 +120,47 @@ include:
       # Adding this script to heredoc to run in SLURM job
       cat << 'EOF' > spack_script.sh
       #!/bin/bash
+      exit() {
+        # Clear all trap handlers so this isn't echo'ed multiple times, potentially
+        # throwing off the CI script watching for this output
+        trap - `seq 1 31`
+
+        # If called without an argument, assume not an error
+        local ec=${1:-0}
+
+        # Echo the snippet the CI script is looking for
+        echo BUILD_STATUS:${ec}
+
+        # Actually exit with that code, although it won't matter in most cases, as CI
+        # is only looking for the string 'BUILD_STATUS:N'
+        builtin exit ${ec}
+      }
+
+      # This will be the catch-all trap handler after arguments are parsed.
+      cleanup() {
+        # Clear all trap handlers
+        trap - `seq 1 31`
+
+        # When 'trap' is invoked, each signal handler will be a curried version of
+        # this function which has the first argument bound to the signal it's catching
+        local sig=$1
+
+        echo
+        echo Exit code $2 caught in build script triggered by signal ${sig}.
+        echo
+
+        exit $2
+      }
+
       export HTTPS_PROXY=http://proxy01.pnl.gov:3128
       export https_proxy=http://proxy01.pnl.gov:3128
-      git clone https://github.com/spack/spack.git $SPACK_INSTALL &&
+      # This is debugging/useful for cleanup
+      # If no `.git` folder in directory and not setup-spack.sh script, 
+      # force clean before clone
+      if [[ ! -d $SPACK_INSTALL/.git && ! -f $SPACK_INSTALL/setup-spack.sh ]]; then
+        rm -rfd $SPACK_INSTALL &&
+        git clone https://github.com/spack/spack.git $SPACK_INSTALL
+      fi &&
       pushd $SPACK_INSTALL &&
       git checkout --detach origin/$SPACK_VERSION &&
       source ./share/spack/setup-env.sh &&
